trigger:
- main

pool: Project-self-hosted-agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Publish build artifacts (client)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/dist'  # Adjust this to the correct output folder
    artifactName: 'client-artifacts'
    publishLocation: 'Container'  # Default location to publish artifacts

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azureConnectionString'
    appName: 'abbas-sleiman-webapp'
    appType: webApp
    package: '$(Build.ArtifactStagingDirectory)/dist'  # Adjust this to the correct output folder
